language: java
jdk:
  -oraclejdk11
script: ant build
deploy:
  - provider: s3
    access_key_id: $vai_key
    secret_access_key: $vai_access
    bucket: 'vaish' 
    region: 'us-east-2'
    skip_cleanup: true
 

